### ISSUE TITLE
Dialog Operators Index

### ISSUE THREAD

**Issue by bigfatnoob** [ai-se/softgoals#103]
| Operator | Issue | Results | Implementation Details |
| --- | --- | --- | --- |
| Variance Jump(Clustering Decisions) | #93 | [Here](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-02/cluster_decision_93_valid/sample.md#decisions-clustered) | Linear Clustering walking from left to right . If values lie within a 25% delta, they are grouped into a single cluster. |
| Smoothing | #94 | [Here](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-02/smoothen_valid/sample.md#smoothened-plot) | Objective values are clustered using scott-knott clusterer and all the objectives belonging to the same cluster is replaced by the mean value in the cluster. |
| Budget Ceiling | #96 | [Here](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-04/early_termination/sample.md) | A budget ceiling was allocated by selecting a value between the max possible budget and max possible budget by 2. If a set of decisions exceeded this budget, the set of decisions is considered invalid. |
| Cost Variation | #95 | [Here](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-07/active_clusters/sample.md) | <ul><li> Assign cost and benefit for each node using a triangular function</li> <li> Run an MOEA to select the best solution for each objective</li> <li>Repeat steps 1 and 2 a 100 times</li><li>  Cluster the best solutions selected on costs, benefits, soft-goals and decisions used</li> <li> Stats of each cluster is reported in the hyperlink table above</li></ul> |
| Exact Solution | #97 |  | More Info and Confirmation Needed |
| Cost Sensitivity | #98 | [Here](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md) | <ul><li> Assign cost and benefit for each node by randomly selecting a value between [val, 2*val, 3*val]</li> <li> Run an MOEA to select the best solution for each objective</li> <li>Repeat steps 1 and 2 a 100 times</li><li>  Cluster the best solutions selected on costs, benefits, soft-goals and decisions used</li> <li> Stats of each cluster is reported in the hyperlink table above</li></ul> |
| Future Solutions ignoring domain constraints | #99 #100 | [Here](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-02/smoothen_invalid/sample.md) | 50% of the time a solution generated is invalid. We are trying to emulate the scenario where people involved in a discussion might be suggesting decisions without considering the possible consequences or influence of other decisions on it. |

**Comment by timm** [comment]
soooo need to talk to you about these
