### ISSUE TITLE
Clusters as CSV

### ISSUE THREAD

**Issue by bigfatnoob** [ai-se/softgoals#105]
First row of the csv file contains the name of the decision and objective. If a column name precedes with **?**, it represents an objective, else it represents a decision.

1) **Node Costs** : [csv](https://github.com/ai-se/softgoals/blob/master/src/csv/cluster_csv/costs.csv) [raw](https://raw.githubusercontent.com/ai-se/softgoals/master/src/csv/cluster_csv/costs.csv)
2) **Node Benefits** : [csv](https://github.com/ai-se/softgoals/blob/master/src/csv/cluster_csv/benefits.csv) [raw](https://raw.githubusercontent.com/ai-se/softgoals/master/src/csv/cluster_csv/benefits.csv)

**Comment by timm** [comment]
i'm seeing what you mean now about combining the peek analysis with the rank analysis
- without rank we have to look at all columns in peek
- with rank, we only have to look at the columns that are found in first few

pause, hang on...
- a premise of the above is that sort analysis uses the same cost variations as rank. hmm.... not practical?

**Comment by bigfatnoob** [comment]
These clusters should not be confused with the previous timm diagrams since those graphs highlighted the significance of the decisions of the model while these clusters provide an insight on the cost and benefit associated with each decision in the model.
