### ISSUE TITLE
Questions about slides

### ISSUE THREAD

**Issue by sei-jklein** [ai-se/softgoals#107]
@timm , @bigfatnoob -

For our internal review, I'm thinking of starting with the diagram on page 4, with slide 3 as backup to explain the process. I can do a simple explanation - find the best solutions, then identify the options that contribute the most to the best solutions. That may be enough for this audience, if not, I'll get into the details on slide 3.

I'll also include an example from some of the result plots that George has generated.

I don't think I will get into the clustering details (slides 5-6). 

The figure in the systematic review paper will be helpful to set context.

Some comments and questions on the presentation you sent, in case I need to get into details:

On Slide 3 (Decision Ranking) 
- Step 2 - "non-dominated solutions" - these are solutions where a change to the decision set reduces one of our objectives (root cost, root benefit, # of soft goals satisfied)?
- Slide 3 - Step 3 - "best" have the highest value for some function f(our objectives)?
- Slide 3 - Step 5 - X=?
- On slide 3 - Step 5 - "An experiment is then run N times". Is this N=Number of Decisions or is N=100 or N=[something else]?
- Terminology: We are using the term "decisions" for the leaves of the tree. This is confusing, since some leaves are AND nodes (no choice possible), and since "decision" implies selecting from a set of OR nodes. Could we call the leaves "options" or "alternatives" or something like that? I think that this will help explaining the method - we need to make decisions by choosing among options. 
- Presentation title: Just to clarify, we haven't done anything with AHP yet. We are trying to figure out how to use that to rank softgoals, relate options to softgoals, or choose among options. The models don't derive from or depend on AHP (yet).

**Comment by bigfatnoob** [comment]
> Step 2 - "non-dominated solutions" - these are solutions where a change to the decision set reduces one of our objectives (root cost, root benefit, # of soft goals satisfied)?

Technically yes. But in our case we do not have 100 non-dominated solutions, we have only around 40 non-dominated ones and the rest is second-grade solutions which are not non-dominated but almost as good as the non-dominated ones

> Slide 3 - Step 3 - "best" have the highest value for some function f(our objectives)? 

Its actually highest percentage of values. Here we select top 20% of the values for the objectives

> Slide 3 - Step 5 - X=?

X is like a loop counter which varies between 1 and length(decisions)

> On slide 3 - Step 5 - "An experiment is then run N times". Is this N=Number of Decisions or is N=100 or N=[something else]?

Here N = 100. I've changed it to K to avoid confusion

> Terminology: We are using the term "decisions" for the leaves of the tree. This is confusing, since some leaves are AND nodes (no choice possible), and since "decision" implies selecting from a set of OR nodes. Could we call the leaves "options" or "alternatives" or something like that? I think that this will help explaining the method - we need to make decisions by choosing among options.

Decision is a term from the MultiObjective Optimization world for an the input variable. Let me know what term you would like to use as a proxy for that and I can change the slides accordingly.

> Presentation title: Just to clarify, we haven't done anything with AHP yet. We are trying to figure out how to use that to rank softgoals, relate options to softgoals, or choose among options. The models don't derive from or depend on AHP (yet)

True. Could not think of a title. Feel free to change it.

**Comment by timm** [comment]
thanks george!

**Comment by sei-jklein** [comment]
@bigfatnoob 
Let me check my understanding of Slides 3 & 4:

Initially, we do not constrain any decisions.
Do 100 times:
 {Create a population with all unconstrained decisions set to random values.
  Run the DE optimizer and get a non-dominated solution. Save the solution.
 }
For the 100 non-dominated solutions*, label the top 20% as BEST. 
Compute a Bayesian support measure for each decision to represent how much the decision contributes to the BEST solutions.
Rank the decisions using the Bayesian metric.
for X = 1 to N (N=number of decisions):
 {Constrain X decisions to the values they had in BEST, leave N-X decisions unconstrained
  Do 100 times:
   {Create a population with all unconstrained decisions set to random values.
     Run the DE optimizer and get a non-dominated solution. Save the solution.
   }
 Compute and save the median and IQR of our objectives for the 100 solutions
 }

Is this close? You have "100" in a couple of places, and I'm trying to map this to the slides.
- Above, you said that there are non-dominated solutions and "second order" solutions that are almost as good - do we treat this all the same? Or do we take only the top 20% of the non-dominated solutions?

**Comment by bigfatnoob** [comment]
Couple of small corrections

> Run the DE optimizer and get a non-dominated solution. Save the solution.

We get the final population and all the the solutions in this population are non-dominated and we save it

> Constrain X decisions to the values they had in BEST, leave N-X decisions unconstrained
> Do 100 times:
> {Create a population with all unconstrained decisions set to random values.
> Run the DE optimizer and get a non-dominated solution. Save the solution.
> }

{
Create a population of size 100
Constrain X decisions to the values they had in BEST, leave N-X decisions as they were. 
Compute and save the median and IQR of our objectives for the 100 solutions
}

> Above, you said that there are non-dominated solutions and "second order" solutions that are almost as good - do we treat this all the same? Or do we take only the top 20% of the non-dominated solutions?

So when we take the top 20% the second order solutions are not considered since most likely the best non-dominated solutions are more than 20%

**Comment by sei-jklein** [comment]
@bigfatnoob 
Thanks! I'll have to rework my explanation and run it by you once more.
