### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by timm** [ai-se/softgoals#111]
john:
- [ ] eval measures to justify this work

**Comment by sei-jklein** [comment]
Government Accountability Office, “Defense Major Automated Information Systems: Cost and Schedule Commitments Need to Be Established Earlier.” United States Government Accountability Office, Report, GAO-15-282, 2015, http://www.gao.gov/products/GAO-15-282 (Accessed 12 Mar 2015).

"A majority of the 20 selected Department of Defense (DOD) major automated information systems (MAIS) programs had not established their first baselines (which consist of a life cycle cost estimate, a schedule estimate, and performance targets) within 2 years from program start; over half met or planned to meet a statutorily established time frame for deploying capabilities."
