### ISSUE TITLE
totally random runs

### ISSUE THREAD

**Issue by timm** [ai-se/softgoals#17]
right now, interp starts at the goals and descents subtrees in random order

to 100% randomized this sh*t, we should take all nodes, sort them in a random order then run "val" on them

**Comment by bigfatnoob** [comment]
Results here : https://github.com/ai-se/softgoals/blob/master/weekly-reports/2015-10-08/random_evals.md
Runtime chart : https://github.com/ai-se/softgoals/blob/master/weekly-reports/2015-10-08/random_runtimes.png
