### ISSUE TITLE
now many softgoal models do we have?

### ISSUE THREAD

**Issue by timm** [ai-se/softgoals#19]
i keep saying 500. but really?

**Comment by bigfatnoob** [comment]
@timm 
- Parseable Models : 115
  - .OOD format - (Parser Implemented) : 19
  - visio format - (Parser in progress) : 96
- Non-Parseable Models : ~30 (Primarily images in jpeg and png format)

**Comment by timm** [comment]
any reason to hand code the non-parseable ones? e.g. they are unusually shaped or unusually big? 

if not, then we seem to have enough otherwise so we could ignore them.

**Comment by bigfatnoob** [comment]
if we can come up with your proposed pyI\* model (#15) we should be able to do it. The ones I have seen dont seem very big. The largest ones are those on .vsd format from Counseling Services.

**Comment by timm** [comment]
then lets ignore the non-parsable ones
