### ISSUE TITLE
need to read

### ISSUE THREAD

**Issue by timm** [ai-se/softgoals#23]
Comparison and evaluation of goal-oriented satisfaction analysis techniques

http://dl.acm.org/citation.cfm?id=2737433.2737525&coll=DL&dl=GUIDE&CFID=717274819&CFTOKEN=27185363

 The purpose of this comparison is to understand the ways in which procedural design choices affect analysis results, and how differences in analysis results could lead to different recommendations over alternatives in the model. Our comparison shows that different satisfaction analysis techniques for goal models can produce variable results, depending on the structure of the model. Comparison findings lead us to recommend the use of satisfaction analysis techniques for goal models as only heuristics for decision making. Our results emphasize investigation into the benefits of satisfaction analysis beyond decision making, namely improving model quality, increasing domain knowledge, and facilitating communication.

**Comment by timm** [comment]
also, need to find **runttimes** of prior work on automatically reasoning about istar models

can you check the reference list shown here for "auto" "verification " reasoning, prove etc? then divide those papers in two and assign you and me to read half each?

http://dl.acm.org/citation.cfm?id=2737433.2737525&coll=DL&dl=GUIDE&CFID=717274819&CFTOKEN=27185363

**Comment by bigfatnoob** [comment]
- Systematic Propagation: 
  - Chung L, Nixon BA, Yu E, Mylopoulos J (2000) Non-functional requirements in software engineering. Kluwer, Norwell
  - Horkoff J, Yu E (2009) Evaluating goal achievement in enterprise modeling—an interactive procedure and experiences. In: Proceedings of 2nd IFIP WG 8.1 working conference on the practice of enterprise modeling (PoEM’09), Springer, LNBIP, vol 39, pp 145–160
  - Giorgini P, Mylopoulous J, Sebastiani R (2005) Goal-oriented requirements analysis and reasoning in the tropos methodology. Eng Appl AI 18(2):159–171
  - Amyot D, Ghanavati S, Horkoff J, Mussbacher G, Peyton L, Yu E (2010) Evaluating goal models within the goal-oriented requirement language. International Journal Intelligent Systems 25(8):841–877
- Metrics over model structure:
  -  Franch X (2006) On the quantitative analysis of agent-oriented models. In: Proceedings of CAiSE’06, Springer, LNCS, vol 4001, pp 495–509
  - Kaiya H, Horai H, Saeki M (2002) AGORA: attributed goal oriented requirements analysis method. In: Proceedings of international requirements engineering conference (RE’02), IEEE Press, p 13
- Simulation Based:
  - Gans D, Schmitz D, Arzdorf T, Jarke M, Lakemeyer G (2004) 
    SNet reloaded: roles, monitoring and agent evolution. In: Proceedings of international bi-conference workshop on agent-oriented information systems (II) (AOIS’04), Springer, LNCS, vol 3508, pp 68–84
  - Wang X, Lesperance Y (2001) Agent-oriented requirements engineering using ConGolog and i*. In: Proceedings of workshop on agent-oriented information systems (AOIS’01), pp 59—78. http://www.aois.org/
- Auto:
  - Giorgini P, Mylopoulous J, Sebastiani R (2005) Goal-oriented requirements analysis and reasoning in the tropos methodology. Eng Appl AI 18(2):159–171
