### ISSUE TITLE
need to write n issues

### ISSUE THREAD

**Issue by timm** [ai-se/softgoals#29]
working on really slow internet.please bust up the following into n issues
- [x] need to augment your last issue report with the decisions u actually made (so jennifer can check our semantics)
- [x] Eric Yu has a student, ?mahomed, who 
       - knows some xml parsing tricks for getting into that xml 
              - please ping eric for mahomet's email)
       - is building a large soft goal trees
              - please ping Mohamed for what he has right now and his best guess of what sizes he expects his stuff to grow into
- [x] need a mutator to grow random case studies, using the statistics offered by Mohamed
- [x] while waiting for moahmed's models, need to debug our rig on the models we have
- [x] need a better clusterer. go to WHERE
- [x] need to include DE's initial pop in the data to be clustered, otherwise you wont see any improvements. so
          -  pop1= de.popFirst 
          -  pop2= de.popFinal and
          - cluster on pop1 and pop2 
- [x] need to ask what questions are we asking
  - [x] if it is "what decisions matter most" then
        -  pop1= de.popFirst 
        -  pop2= de.popFinal and
        -  "what matters" is the delta seen in a decision tree between class1=pop1 and class2=pop2
  - [x] it is "what decisions lead to better results" do the the above  (cluster on pop1 and pop2 )
  - [x] is it "is DE or some other optimizer good" then need stats on pop0 and pop.final found by
     other optimizers.
  - [x] if it is "our process finds the most informative tree" then need stats of depth of tree branches
    found by decision tree vs number of conflicts in the models

**Comment by bigfatnoob** [comment]
#30 
#31
#32
#33
#34
#35
