### ISSUE TITLE
checking the interpreter

### ISSUE THREAD

**Issue by timm** [ai-se/softgoals#4]
jennifer writes:
If you want more detail, see part of the evaluation section of my REJ2014 paper:  http://www.cs.utoronto.ca/~jenhork/Papers/InteractiveAnalysisREJ14.pdf  This paper also references other papers that use the same case.  

now we have to check if my interpreter is anything like her's https://github.com/ai-se/softgoals/blob/master/interpret.md

**Comment by bigfatnoob** [comment]
![screen shot 2015-08-22 at 2 18 25 pm](https://cloud.githubusercontent.com/assets/5582924/9425278/dc678e3e-48d8-11e5-9085-6100e8d13da1.png)

We might need to manually construct a json or xml that complies with her format such that we can send it into your interpreter.  

Furthermore, helps and hurts could be used as constraints for the model.

**Comment by timm** [comment]
json xml would just be intermediaries. the real underlying representing is a gragh G with directed arcs A and nodes N 
- where arcs have types (makes, breaks, helps, hurts) 
-  nodes have types (and,or) and value = (None,t,f) 

initially values are None and then we stagger around the graph assigning t,f

pause

at least, thats how i saw it pre-jennifer in 2004. how much of her thinking does _not_ marry into the above?

**Comment by timm** [comment]
btw, expectation management. we are going to spend weeks/months working out the semantics of this interpreter.

**Comment by bigfatnoob** [comment]
What I have understood reading Dr Horkoff's literature is that 
- She follows the i\* model
- Actors(roles/agents) are high level entities that contains goals / soft-goals / tasks / resources
- I assume that we will be representing these(goals/soft-goals) as nodes
- Arcs(edges) connect these nodes and these can be of type
  - **and** / **or** if the destination is a goal
  - **make**/**break**/**help**/**hurt** if the destination is a softgoal

I think types(and/or) quantifies edges rather than nodes if my above understanding of the framework is right? Thoughts?

**Comment by jenhork** [comment]
Hello Tim and George,

I think I'm jumping in the middle of a conversation here, but perhaps I can
help.   In my work, I followed i_, but had to created my own formal
semantics (as i_ doesn't have one by default).  I extended and adapted the
interpretation made by J. Mylopoulos et al. in the Tropos framework.   My
formal semantics for i\* can be found in my ER paper:
Jennifer Horkoff, Eric Yu, Finding Solutions in Goal Models:  An
Interactive Backward Reasoning Approach, ER'10 Springer (Slides)
http://www.cs.toronto.edu/~jenhork/Papers/ER_Horkoff.pdf
Also in our REJ'14 journal paper:
Jennifer Horkoff, Eric Yu: Interactive goal model analysis for early
requirements engineering, Requirements Engineering, August 2014. Springer.
http://www.cs.utoronto.ca/~jenhork/Papers/InteractiveAnalysisREJ14.pdf

And yes, all elements are nodes (goals, softgoals, tasks, resources).
Actors are there, but not as yet used for analysis.

Edges can be refinement (AND or OR), contribution (make, break, help, hurt,
unknown, some+, some-), or dependency.

Each node has a qualitative analysis values which is determined by my label
propagation algorithm.  The possibilities are:  none, satisfied (S),
partially satisfied (PS), denied (D), partially denied (U), and unknown (U).

The algorithms and rules are all about determining these labels for all
nodes, given a starting graph and some starting labels.  In some cases my
approach is interactive:  it stops and ask the users to resolve conflicting
or partial evidence.  The underlying implementation used SAT, and a later
version for a slightly different purpose used SMT (RE'14).

Having said all that, the counseling service models we've shared are all
encoded in Visio, using however microsoft encodes graphs.  If one were
interested in applying my i\* reasoning algorithms, the visio xml would
first have to be converted to some format matching the concepts and
semantics above.    This was done in the OpenOME tool (created after the
counseling service models were made).  The OpenOME metamodel is in my long
journal paper, link above, if that helps.

I'm at RE'15 all week, but can answer more questions later, if I can be
helpful.

Best,

Jennifer

**Comment by timm** [comment]
I did a lot of reasoning over (possibly) contradictory models in my ph.d. and my conceit is that, with a few nondeterminacy tricks, i can spec the semantics simpler than alternate descriptions that demand a deterministic solution. :yum:

at least, that's where i got to in 2004 with eliza chiang. now that @jenhork has improved and clarified much i'm going to have to revisit all that again. :frowning: 

we'll see if i am being a fool   :stuck_out_tongue_winking_eye:  or not :laughing: 

!!

t

**Comment by timm** [comment]
btw, totally riffing at github being a way to organize colloberation
