### ISSUE TITLE
Mapping to decisions, objectives and constraints

### ISSUE THREAD

**Issue by bigfatnoob** [ai-se/softgoals#6]
Based on what I have read so far[1,2], I presume that we should model our optimization problem as follows
**decisions** : Tasks/Resources should be marked as decisions as these can be configured in a system
**objectives** : Softgoals 
**constraints** : Goals. Since while optimizing for the softgoals we should make sure that the goals are not compromised.

[1] http://www.cs.toronto.edu/~jenhork/Papers/ER_Horkoff.pdf
[2] http://www.cs.utoronto.ca/~jenhork/Papers/InteractiveAnalysisREJ14.pdf

@timm your thoughts?

**Comment by timm** [comment]
decisions: bottom of trees
goals: top of trees

**Comment by bigfatnoob** [comment]
Implemented mapping of tasks and resources to decisions. Agents are ignored for now.
