### ISSUE TITLE
Implement graph traversal

### ISSUE THREAD

**Issue by bigfatnoob** [ai-se/softgoals#7]
Good Src : https://www.python.org/doc/essays/graphs/

**Comment by bigfatnoob** [comment]
Partly implemented random graph traversal. Need to better implement the semantics for contributions and clash between dependency and decompositions

**Comment by timm** [comment]
we really need a session where we closely read jennifer's paper to check that her semantics does not contradict ours.

**Comment by jenhork** [comment]
If you send me something I can actually read sort of easily, I can visually
check to see if anything is noticeably off.   This is for forwards
analysis.  For backwards, it's really hard to check manually!

Best,

Jennifer

**Comment by bigfatnoob** [comment]
Should be addressed by #15
