### ISSUE TITLE
Review diagrams

### ISSUE THREAD

**Issue by timm** [ai-se/softgoals#92]
Dr Menzies,

Generated the following diagram using graphviz. Let me know your thoughts. Green is the path you should be taking

Figure : https://github.com/ai-se/softgoals/blob/master/src/img/visualize/sample_choices.png
Raw : https://raw.githubusercontent.com/ai-se/softgoals/master/src/img/visualize/sample_choices.png
Report : https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-02-28/visualize/sample.md

**Comment by timm** [comment]
i'd need  a little background on how to walk these diagrams. skype call tomorrow?

**Comment by bigfatnoob** [comment]
Yeah sure. Let me know when you are free

**Comment by timm** [comment]
i'm home all after noon.  skype me or do hang outs when u have 10 minutes spare?

**Comment by bigfatnoob** [comment]
Updated Results based on generating random samples based on induction

### [Figure](https://github.com/ai-se/softgoals/blob/master/src/img/star1_induced/sample_choices.png)

### [Raw](https://raw.githubusercontent.com/ai-se/softgoals/master/src/img/star1_induced/sample_choices.png)

### [Report](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-02-29/star1_induced/sample.md)

**Comment by bigfatnoob** [comment]
Considering only valid generations

### [Figure](https://github.com/ai-se/softgoals/blob/master/src/img/valid_generations/sample_choices.png)

### [Raw](https://raw.githubusercontent.com/ai-se/softgoals/master/src/img/valid_generations/sample_choices.png)

### [Report](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-01/valid_generations/sample.md)

@timm your thoughts on the [report](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-01/valid_generations/sample.md)?
Now while randomly thrashing(presetting the top X decisions) around I generate only valid solutions. Previously I was generating a combination of valid and invalid solutions
