### ISSUE TITLE
Dialog operator #1: the variance jump

### ISSUE THREAD

**Issue by timm** [ai-se/softgoals#93]
when walking thru the decisions linearly, if the next N steps lead to an increase in variance, then a decrease, present all N to the user at one go.

**Comment by bigfatnoob** [comment]
### Valid Generations while Random Trashing

#### [Report](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-02/cluster_decision_93_valid/sample.md#decisions-clustered)

### Valid + Invalid Generations while Random Trashing

#### [Report](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-02/cluster_decision_93_invalid/sample.md#decisions-clustered)

Here change in median was used in place of change in variance as selecting a 'delta' for change in variance results in too many clusters. For this experiment delta = 25%. i.e

```
if abs(old - new) > delta * old:
   old and new belong to different cluster
else:
   old and new belong to same cluster
```

@timm Thoughts?
