### ISSUE TITLE
Dialog operator #2: smoothing (bunching and early stop)

### ISSUE THREAD

**Issue by timm** [ai-se/softgoals#94]
run over all the steps in the b^2/(b+r)  till the end (as done now)

for x decisions repeated n times, this will give you x*n numbers. run scott knot of all x, looking for sane breaks in the curves. this will turn our squiggly lines into a smaller number of straight lines

then
- [ ] **Bunch**: all decisions till the next break are really one set. present them as one
- [ ] **Early stop**: at some point, there will be not change from here to the end. do early stop

**Comment by sei-jklein** [comment]
I'm not following the suggestion - how does the x*n numbers relate to the results we generate in the baseline approach?

Also, how do you know that there will be no later change?

**Comment by timm** [comment]
@sei-jklein the operator here is ...
-   its midnight
-   you've been arguing for hours
-  you've nailed down half to two-thirds of the decisions
-   you currently have a total cost/benefit of X/Y
-   you look at head at everything left to decide and realize its just rearranging deckchairs on the cruise liner. i.e. very little additional  benefit benefit is achievable
-  so you call it a night , flip a coin for the stuff that is left or just ask anyone "who wants anything of what's left"
- and everyone gets to get some sleep

**Comment by bigfatnoob** [comment]
### Valid Generations while Random Trashing

#### [Report](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-02/smoothen_valid/sample.md#smoothened-plot)

### Valid + Invalid Generations while Random Trashing

#### [Report](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-02/smoothen_invalid/sample.md#smoothened-plot)

**Method**: Simulations for all decisions clustered using scott-knot. New median and iqr is computed as mean of median and iqr of all the simulations within the cluster.

@timm Thoughts?

**Comment by timm** [comment]
need to show these to @sei-jklein 

jim- we spoke about early termination before. look at  the following. here, slopes only change if they are statistically significantly different (reduces noise in the curves)

note the early stopping points: after 4 decisions there is this point where you get most of what you can get later on, with least variance. if a facilitator had that information, then could they not argue for a stop at that point?

![image](https://cloud.githubusercontent.com/assets/29195/13502668/e0b86ae0-e139-11e5-995c-8520fbaadcc5.png)
