### ISSUE TITLE
Dialog operator #3: budget ceiling

### ISSUE THREAD

**Issue by timm** [ai-se/softgoals#96]
add a budget ceiling number that is selected randomly by the DE over the range min to max:

max = sum of all costs in entire mode
min = max/10

during the run. if cost > ceiling then stop. and by "cost" here i mean the sum of cost of all nodes currently used in the simulation.

**Comment by sei-jklein** [comment]
I'm not understanding "sum of all costs in entire mode".

However, establishing a maximum allowable cost as a global constraint is a good filter for stopping early.

**Comment by bigfatnoob** [comment]
#### [Early Termination Report](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-04/early_termination/sample.md)

#### [No Termination Report](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-02/smoothen_valid/sample.md)

Changes to notice:
- The plot starts stabilizing earlier than before now.
- Ordering of decisions have changed slightly now
