### ISSUE TITLE
Dialog operator #5: Baby wants his toy

### ISSUE THREAD

**Issue by timm** [ai-se/softgoals#97]
@bigfatnoob : dont implement this one (unless SEI wants it). its too evil.

not matter what, X has to be in the final solution. move heaven and hell to make it so.

**Comment by sei-jklein** [comment]
Maybe a more constructive approach: For a particular specified solution, how can we assess the relative goodness? Is this solution sitting alone in a trough, and a small change might make the solution much better? Or is it sitting on a plateau with no objective difference from its neighbors, and so small changes don't have much impact?

Do we have a measure of the "distance" between two solutions, e.g., how many decisions are different?

**Comment by timm** [comment]
so some distance measure that is not just the syntactic delta between items, but also some measure of the effect on the goals of jumping between them

george.. is the b^2/(b+r) distance insightful here?

**Comment by bigfatnoob** [comment]
The bayesian support(b^2/b+r) looks like a good criterion to categorize the decisions.

**Comment by sei-jklein** [comment]
There are two measures here: one is the relative goodness of a solution, the other is a measure of how different is the path that gets us to two adjacent solutions. If changing one constituent decision turns a bad solution into a significantly better solution, that could be a good thing in the process.
