### ISSUE TITLE
Dialog Operator #7: Cost Sensitivity

### ISSUE THREAD

**Issue by sei-jklein** [ai-se/softgoals#98]
For each alternative, choose N cost values, sampled from the interval (input cost, 3x input cost). N is a small number like 3 or 5.

This gives us R = N \* number of nodes. 

Run the optimizer with all costs set to the input values. Repeat R times, changing one cost value each time. Cluster the results. 

(This won't actually require R runs, since you can abort any run that skips the node that you are twiddling.)

This is similar to the Twiddle the Cost operator, but with direct cause-and-effect visibility.

**Comment by bigfatnoob** [comment]
### Clusters

| [1](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-1) | [2](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-2) | [3](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-3) | [4](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-4) | [5](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-5) | [6](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-6) | [7](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-7) | [8](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-8) | [9](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-9) | [10](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-10) | [11](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-11) | [12](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-12) | [13](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-13) | [14](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-14) | [15](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-15) | [16](https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-14/sensitivity/sample.md#cluster-16) |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
