### ISSUE TITLE
Dialog operator #6a: assess solutions across the space of all future solutions

### ISSUE THREAD

**Issue by bigfatnoob** [ai-se/softgoals#99]
... which i what we have been doing all along....

**Comment by bigfatnoob** [comment]
Ignoring constraints and random generations.

https://github.com/ai-se/softgoals/blob/master/weekly-reports/2016-03-02/smoothen_invalid/sample.md

**Comment by timm** [comment]
? say what

 Ignoring constraints and random generations.

**Comment by bigfatnoob** [comment]
@timm 
50% of the time, pick the remaining solutions at random with no consideration of domain constraints or topology. #100

Thought these two(#99 and #100) went together. Hence pasted it here
